services: 
  backend:
    container_name: backend
    image: node:lts
    working_dir: /app
    command: sh -c "npm install && npm run migration:run && npm run seed:run"
    environment:
      - PORT=3000
    ports:
      - "8080:3000"
      - "9229:9229"
    volumes:
      - ".:/app"
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
